export const environment = {
  production: true,
  apiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MjcyODA0Yy04ZDBlLTRjNzktODIyMS0yNmJhNTk0MzVlMTYiLCJlbWFpbCI6IkJydW5vdmluaW1lbGxvUEBob3RtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJCcnVubyIsIm5iZiI6MTY5Njg2Mjc1MywiZXhwIjoxNjk2ODkxNTUzLCJpYXQiOjE2OTY4NjI3NTMsImlzcyI6ImVBZ2VuZGEiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0In0.UyHDQi8wfK-AnQleBGEe8PLUKR_s7mIoPxqrX0VZCo0'
}