export const environment = {
  production: true,
  apiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MjcyODA0Yy04ZDBlLTRjNzktODIyMS0yNmJhNTk0MzVlMTYiLCJlbWFpbCI6IkJydW5vdmluaW1lbGxvUEBob3RtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJCcnVubyIsIm5iZiI6MTY5NjUyOTM0MCwiZXhwIjoxNjk2NTU4MTQwLCJpYXQiOjE2OTY1MjkzNDAsImlzcyI6ImVBZ2VuZGEiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0In0.sHqjqOsQwTXfwPI6Qu81p43CvqFwIdhP-0stjBE2HNA'
}