export const environment = {
  production: false,
  apiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MjcyODA0Yy04ZDBlLTRjNzktODIyMS0yNmJhNTk0MzVlMTYiLCJlbWFpbCI6IkJydW5vdmluaW1lbGxvUEBob3RtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJCcnVubyIsIm5iZiI6MTY5NzU2MDYwMSwiZXhwIjoxNjk3NTg5NDAxLCJpYXQiOjE2OTc1NjA2MDEsImlzcyI6ImVBZ2VuZGEiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0In0.TUAFjiq2XEQ7DmBq8hmvVkzj7H94wFhPI4VCkWcGGPM'
}
